hostapp-update.bb: Redesign running hooks
When updating a system we change the way we run the hooks as it follows:
1. spawn a container from the 'next' host OS in which we run the new hooks
2. if any of the hooks fail run the current hooks to try to recover system

As well RESIN_HOSTAPP_HOOKS_LIST is not used anymore.

Signed-off-by: Andrei Gherzan <andrei@resin.io>

diff --git a/meta-resin-common/recipes-containers/hostapp-update/files/hostapp-update b/meta-resin-common/recipes-containers/hostapp-update/files/hostapp-update
--- a/meta-resin-common/recipes-containers/hostapp-update/files/hostapp-update
+++ b/meta-resin-common/recipes-containers/hostapp-update/files/hostapp-update
@@ -7,8 +7,6 @@ remote_image=""
 reboot=0
 hooks=1
 
-hooks_list="@RESIN_HOSTAPP_HOOKS_LIST@"
-
 while getopts 'f:i:rn' flag; do
 	case "${flag}" in
 	f) local_image=$(realpath "${OPTARG}") ;;
@@ -83,20 +81,27 @@ cur_counter=0
 if [ -f "/mnt/sysroot/active/counter" ]; then
 	cur_counter=$(cat /mnt/sysroot/active/counter)
 fi
-echo $(($cur_counter + 1)) > "$SYSROOT/counter.new"
+echo $((cur_counter + 1)) > "$SYSROOT/counter.new"
 sync -f "$SYSROOT"
 mv "$SYSROOT/counter.new" "$SYSROOT/counter"
 sync -f "$SYSROOT"
 
-# Run all the defined hooks in the host OS we update to
 if [ "$hooks" = 1 ]; then
-	hooks_list_new="/tmp/$(basename $hooks_list).new"
-	balena cp "$CONTAINER_ID:$hooks_list" "$hooks_list_new"
-	while read entry; do
-		echo "Running $(basename $entry) hook from next OS..."
-		balena cp "$CONTAINER_ID:$entry" "/tmp/$(basename $entry)"
-		"/tmp/$(basename $entry)" "$CONTAINER_ID"
-	done < "$hooks_list_new"
+	# Run all the defined hooks in the host OS we update to
+	if balena run -v /mnt:/mnt -v /mnt/sysroot/inactive:/mnt/sysroot/active --rm "$HOSTAPP_IMAGE" bash -ec "for hook in /etc/hostapp-update-hooks.d/*; do \$hook; done"; then
+		echo "New hooks ran successfully."
+	else
+		# Something went wrong with the new hooks. Run the current ones to
+		# cleanup the system.
+		echo "Failed to run the new hooks. Running current hooks... "
+		for hook in /etc/hostapp-update-hooks.d/*; do
+			# Try to recover as much as possible so run all hooks without
+			# failing on error
+			"$hook" || true
+		done
+		echo "Update failed."
+		exit 1
+	fi
 fi
 
 if [ "$reboot" = 1 ]; then
