hostapp-update: make sure an image was passed as a parameter
Signed-off-by: Petros Angelatos <petrosagg@gmail.com>

diff --git a/meta-resin-common/recipes-containers/hostapp-update/files/hostapp-update b/meta-resin-common/recipes-containers/hostapp-update/files/hostapp-update
--- a/meta-resin-common/recipes-containers/hostapp-update/files/hostapp-update
+++ b/meta-resin-common/recipes-containers/hostapp-update/files/hostapp-update
@@ -15,6 +15,11 @@ while getopts 'f:i:r' flag; do
 	esac
 done
 
+if [ "$local_image" =  "" ] && [ "$remote_image" = "" ]; then
+	echo "At least one of -f or -i is required"
+	exit 1
+fi
+
 export DOCKER_HOST="unix:///var/run/docker-host.sock"
 SYSROOT="/mnt/sysroot/inactive"
 
