Fetch assets from TFTP when network booting
Signed-off-by: Michal Toman <michalt@balena.io>

diff --git a/meta-balena-common/recipes-core/initrdscripts/files/imagefetch b/meta-balena-common/recipes-core/initrdscripts/files/imagefetch
--- a/meta-balena-common/recipes-core/initrdscripts/files/imagefetch
+++ b/meta-balena-common/recipes-core/initrdscripts/files/imagefetch
@@ -16,15 +16,28 @@ imagefetch_enabled() {
 	return 1
 }
 
-export BALENA_IMAGE="balena-image.img.gz"
-
 # NETWORK_BOOT_SERVER is set in the dynamicip module
 imagefetch_run() {
 	# Fetch balena image from tftp
-	cd /rootfs || exit 1
+	mkdir /opt || exit 1
+	. /etc/resin-init-flasher.conf
+	BALENA_IMAGE=$(basename "${balena_tftp_image}")
 	info "Fetching ${BALENA_IMAGE} from ${NETWORK_BOOT_SERVER}"
-	if ! tftp -g -l "${BALENA_IMAGE}" "${NETWORK_BOOT_SERVER}"; then
+	if ! tftp -g -r "${balena_tftp_image}" -l "/opt/${RESIN_IMAGE}" "${NETWORK_BOOT_SERVER}"; then
 		fail "Failed fetching balena image"
 		exit 1
 	fi
+
+	BALENA_BOOT=$(basename "${balena_tftp_boot}")
+	info "Fetching ${BALENA_BOOT} from ${NETWORK_BOOT_SERVER}"
+	if ! tftp -g -r "${balena_tftp_boot}" -l "/opt/${BALENA_BOOT}" "${NETWORK_BOOT_SERVER}"; then
+		fail "Failed fetching balena boot partition"
+		exit 1
+	fi
+	mkdir -p "/mnt/boot"
+	cd "/mnt/boot"
+	tar xzf "/opt/${BALENA_BOOT}"
+	# With resin-image-flasher file in place we would need to move config.json around
+	rm -f "/mnt/boot/resin-image-flasher"
+	rm -f "/opt/${BALENA_BOOT}"
 }
