initrdscripts/machineid: Use partition paths based on UUIDs when available
This commit also restructures a little bit the module for clarity.

Signed-off-by: Andrei Gherzan <andrei@balena.io>

diff --git a/meta-balena-common/recipes-core/initrdscripts/files/machineid b/meta-balena-common/recipes-core/initrdscripts/files/machineid
--- a/meta-balena-common/recipes-core/initrdscripts/files/machineid
+++ b/meta-balena-common/recipes-core/initrdscripts/files/machineid
@@ -2,36 +2,36 @@
 
 machineid_enabled() {
     # On flasher we don't need persistent machine-id
+    # shellcheck disable=SC2154
     if [ "$bootparam_flasher" = "true" ]; then
         echo "[INFO] Flasher detected. Avoiding persistent machine-id."
-        return 1
-    fi
-
-    start="$(date +%s)"
-    end="$start"
-    while [ ! -L "/dev/disk/by-label/resin-state" ]; do
-        if [ $((end - start)) -le 600 ]; then
-            sleep 0.05 && end=$((end + 1))
-        else
-            echo "[ERROR] Timeout while waiting for resin-state label to appear."
-            echo "[ERROR] Not able to mount resin-state, machine-id will not be persistent"
-            return 1
-        fi
-    done
-
-    if ! mount -t ext4 /dev/disk/by-label/resin-state "$ROOTFS_DIR"/mnt/state; then
-        echo "[ERROR] Not able to mount resin-state, machine-id will not be persistent"
         return 1
     fi
     return 0
 }
 
 machineid_run() {
-    # setup the environment
-    if [ ! -e "$ROOTFS_DIR"/mnt/state/machine-id ]; then
-        touch "$ROOTFS_DIR"/mnt/state/machine-id
+    # Mount the state partition - that's where we store the machine_id
+    state_partition_path="$(get_cmdline_uuid_label_path "resin-state")"
+    if ! wait4file "$state_partition_path" "300"; then
+        error "Timeout while waiting for resin-state partition to be detected."
+        error "Not able to mount resin-state, machine-id will not be persistent."
+	return
+    fi
+
+    if ! mount -t ext4 "$state_partition_path" "$ROOTFS_DIR"/mnt/state; then
+        error "Not able to mount resin-state, machine-id will not be persistent."
+        return
     fi
 
     # Mount machine-id
-    mount -o bind "$ROOTFS_DIR"/mnt/state/machine-id "$ROOTFS_DIR"/etc/machine-id
+    if [ ! -e "$ROOTFS_DIR"/mnt/state/machine-id ]; then
+        touch "$ROOTFS_DIR"/mnt/state/machine-id
+    fi
+    if ! mount -o bind "$ROOTFS_DIR"/mnt/state/machine-id "$ROOTFS_DIR"/etc/machine-id; then
+	    error "Error while mounting persistent machine-id."
+	    return
+    fi
+    info "Persistent machine-id mounted."
+
 }
