balena-unique-key: Minor improvements
If for whatever reason the key can't be generatei, fail the script as
opposed to blindly continue it and subsequently the boot services. Also
avoid the shellcheck SC1091 because the source path only makes sense at
runtime.

Signed-off-by: Andrei Gherzan <andrei@balena.io>

diff --git a/meta-resin-common/recipes-support/balena-unique-key/balena-unique-key/balena-unique-key b/meta-resin-common/recipes-support/balena-unique-key/balena-unique-key/balena-unique-key
--- a/meta-resin-common/recipes-support/balena-unique-key/balena-unique-key/balena-unique-key
+++ b/meta-resin-common/recipes-support/balena-unique-key/balena-unique-key/balena-unique-key
@@ -34,6 +34,7 @@ while [ $# -gt 0 ]; do
     shift
 done
 
+# shellcheck disable=SC1091
 source /usr/sbin/resin-vars
 
 if [ -z "$CONFIG_PATH" ]; then
@@ -48,7 +49,10 @@ fi
 
 if [ -z "$key" ]; then
     echo "[INFO] balena-unique-key: $key_name missing from config file. Generating..."
-    key=$(openssl rand -hex 16)
+    if ! key=$(openssl rand -hex 16); then
+        echo "[ERROR] balena-unique-key : Failed to generate the random key."
+	exit 1
+    fi
     generated_json=$(jq ".$key_name=\"$key\"" "$CONFIG_PATH")
     echo "$generated_json" > "$CONFIG_PATH.tmp"
     sync "$CONFIG_PATH.tmp"
