resin-unique-key: Avoid overwritting empty or invalid config.json
Fixes #1262

Change-type: minor
Changelog-entry: Don't let resin-unique-key rewrite config.json
Signed-off-by: Andrei Gherzan <andrei@balena.io>

diff --git a/meta-resin-common/recipes-support/resin-unique-key/resin-unique-key/resin-unique-key b/meta-resin-common/recipes-support/resin-unique-key/resin-unique-key/resin-unique-key
--- a/meta-resin-common/recipes-support/resin-unique-key/resin-unique-key/resin-unique-key
+++ b/meta-resin-common/recipes-support/resin-unique-key/resin-unique-key/resin-unique-key
@@ -34,25 +34,25 @@ while [ $# -gt 0 ]; do
     shift
 done
 
-source /usr/sbin/resin-vars --config-path "$CONFIG_PATH"
+source /usr/sbin/resin-vars
 
 if [ -z "$CONFIG_PATH" ]; then
     echo "[ERROR] resin-unique-key : Please set CONFIG_PATH environment variable."
     exit 1
 fi
 
-if [ ! -s "$CONFIG_PATH" ]; then
-    echo "[INFO] resin-unique-key: Config file is missing. Creating.."
-    echo '{}' > "$CONFIG_PATH"
-else
-    read key <<<$(jq -r ".$key_name //empty" "$CONFIG_PATH")
+if ! key=$(jq -r ".$key_name //empty" "$CONFIG_PATH"); then
+    echo "[ERROR] resin-unique-key : Error parsing the CONFIG_PATH json. Is it a valid json?"
+    exit 1
 fi
 
 if [ -z "$key" ]; then
     echo "[INFO] resin-unique-key: $key_name missing from config file. Generating..."
     key=$(openssl rand -hex 16)
     generated_json=$(jq ".$key_name=\"$key\"" "$CONFIG_PATH")
-    echo "$generated_json" > "$CONFIG_PATH"
+    echo "$generated_json" > "$CONFIG_PATH.tmp"
+    sync "$CONFIG_PATH.tmp"
+    mv "$CONFIG_PATH.tmp" "$CONFIG_PATH"
 else
     echo "[INFO] resin-unique-key : Device already has $key_name assigned."
 fi
