resin-init-flasher: Do not  hardcode the path to the internal boot device
Make sure the internal boot device we mount is the one we have just
programmed - using the resin-boot label might clash.

Change-type: patch
Signed-off-by: Alex Gonzalez <alexg@balena.io>

diff --git a/meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher b/meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher
--- a/meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher
+++ b/meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher
@@ -48,6 +48,8 @@ BALENA_BOOTLOADER_CONFIG=resinOS_uEnv.txt
 LUKS=0
 SECUREBOOT_SETUP=0
 
+. /usr/libexec/os-helpers-fs
+
 function clean {
     echo "[resin-init-flasher] Cleanup."
     umount $INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT > /dev/null 2>&1 || true
@@ -184,9 +186,6 @@ if command -v efivar && [ -d /sys/firmware/efi ]; then
 fi
 
 if [ "$LUKS" = "1" ]; then
-    # Include FS helpers for repartitioning
-    . /usr/libexec/os-helpers-fs
-
     # Include TPM2 helpers
     . /usr/libexec/os-helpers-tpm2
 
@@ -357,8 +356,13 @@ fi
 mkdir -p $INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT
 inform "Mounting internal device boot partition."
 
-if ! mount /dev/disk/by-label/resin-boot $INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT; then
-    fail "Failed to mount disk labeled as 'resin-boot'."
+BOOT_MOUNT=$(get_dev_path_in_device_with_label "${internal_dev}" resin-boot)
+if [ -n "${BOOT_MOUNT}" ]; then
+    if ! mount "${BOOT_MOUNT}"  "${INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT}"; then
+        fail "Failed to mount disk labeled as 'resin-boot'."
+    fi
+else
+    fail "Internal boot partition (resin-boot) not found in ${internal_dev}"
 fi
 
 if [ "$LUKS" = "1" ]; then
