Ship separate GRUB images for secure boot
Shipping a single image with signature checks enabled will enforce
the signatures on non-secure-boot systems as well. GRUB does not have
a simple method to check whether secure boot is enabled that could
be embedded with the default built-in config.

With this patch we build two separate images - one enforcing
the signatures and the other one not, keeping the original behavior.
HUP and flasher both can detect if secure boot is enabled so they
put the correct image in place when installing/updating GRUB.

Change-type: patch
Signed-off-by: Michal Toman <michalt@balena.io>

diff --git a/meta-balena-common/recipes-support/hostapp-update-hooks/files/99-resin-grub b/meta-balena-common/recipes-support/hostapp-update-hooks/files/99-resin-grub
--- a/meta-balena-common/recipes-support/hostapp-update-hooks/files/99-resin-grub
+++ b/meta-balena-common/recipes-support/hostapp-update-hooks/files/99-resin-grub
@@ -61,6 +61,25 @@ if [ ! -d /sys/firmware/efi ] ; then
 else
     # Remove legacy grub
     rm -rf "$BALENA_BOOT_MOUNTPOINT/grub" || true
+
+    # Put the secure boot GRUB variant in place or remove it when applicable
+    EFI_BOOT_DIR="${BALENA_BOOT_MOUNTPOINT}/EFI/BOOT/"
+    for EFI_BINARY in "${EFI_BOOT_DIR}/"*.efi; do
+        if [ "${EFI_BINARY}" = "${EFI_BOOT_DIR}/*.efi" ]; then
+            # Nothing matched the glob
+            break
+        fi
+
+        EFI_BINARY_SECUREBOOT="${EFI_BINARY}.secureboot"
+        if [ "${type}" = "crypt" ]; then
+            # If this fails it is a fatal error - the secure boot variant
+            # must be in place when LUKS is enabled
+            mv "${EFI_BINARY_SECUREBOOT}" "${EFI_BINARY}"
+        else
+            # This can safely fail if the secure boot variant does not exist
+            rm -f "${EFI_BINARY_SECUREBOOT}" || :
+        fi
+    done
 fi
 
 grub_cfg=$(find -L $BALENA_BOOT_MOUNTPOINT -name grub.cfg)
diff --git a/meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher b/meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher
--- a/meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher
+++ b/meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher
@@ -498,6 +498,27 @@ if [ -f "${EXTERNAL_DEVICE_BOOT_PART_MOUNTPOINT}/${BALENA_BOOTLOADER_CONFIG}" ];
         cp $EXTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/$BALENA_BOOTLOADER_CONFIG $INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT
 fi
 
+# Put the GRUB EFI binary in place or remove it when applicable
+if [ "${EFI}" = "1" ]; then
+    INTERNAL_BOOTLOADER_DIR=$(dirname "${INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT}/${INTERNAL_DEVICE_BOOTLOADER_CONFIG_PATH}")
+    for EFI_BINARY in "${INTERNAL_BOOTLOADER_DIR}/"*.efi; do
+        if [ "${EFI_BINARY}" = "${INTERNAL_BOOTLOADER_DIR}/*.efi" ]; then
+            # Nothing matched the glob
+            break
+        fi
+
+        EFI_BINARY_SECUREBOOT="${EFI_BINARY}.secureboot"
+        if [ "${LUKS}" = "1" ]; then
+            # If this fails it is a fatal error - the secure boot variant
+            # must be in place when LUKS is enabled
+            mv "${EFI_BINARY_SECUREBOOT}" "${EFI_BINARY}"
+        else
+            # This can safely fail if the secure boot variant does not exist
+            rm -f "${EFI_BINARY_SECUREBOOT}" || :
+        fi
+    done
+fi
+
 # Give a chance for the device to register
 STARTTIME=$(date +%s)
 ENDTIME="$STARTTIME"
