hostapp-update-hooks: check for logging helper
Older balenaOS version (before v2.58) do not contain the logging helper
in the rootfs and the new OS hooks fail to execute.

This commit checks for the file existence before using it, and defines
the logging functions when not detected.

Change-type: patch
Signed-off-by: Alex Gonzalez <alexg@balena.io>

diff --git a/meta-balena-common/recipes-support/hostapp-update-hooks/files/hostapp-update-hooks b/meta-balena-common/recipes-support/hostapp-update-hooks/files/hostapp-update-hooks
--- a/meta-balena-common/recipes-support/hostapp-update-hooks/files/hostapp-update-hooks
+++ b/meta-balena-common/recipes-support/hostapp-update-hooks/files/hostapp-update-hooks
@@ -2,8 +2,33 @@
 
 set -o errexit
 
-# shellcheck disable=SC1091
-. /usr/libexec/os-helpers-logging
+if [ -f "/usr/libexec/os-helpers-logging" ]; then
+	# shellcheck disable=SC1091
+	. /usr/libexec/os-helpers-logging
+else
+	log () {
+		_level="$1"
+		_message="$2"
+		printf "[%s][%s] %s\n" "$ME" "$_level" "$_message" >&2
+		echo "$@"
+	}
+	fail () {
+		error "$1"
+		exit 1
+	}
+
+	error () {
+		log "ERROR" "$1"
+	}
+
+	warn () {
+		log "WARN" "$1"
+	}
+
+	info () {
+		log "INFO" "$1"
+	}
+fi
 # shellcheck disable=SC1091
 [ -f "/usr/sbin/balena-config-defaults" ] && . /usr/sbin/balena-config-defaults
 
