os-helpers-fs: Add helper functions for relabelling filesystems
Signed-off-by: Alex Gonzalez <alexg@balena.io>

diff --git a/meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-fs b/meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-fs
--- a/meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-fs
+++ b/meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-fs
@@ -93,6 +93,13 @@ get_state_path_from_label() {
 	return 1
 }
 
+# Output the filesystem label for the specified block device.
+# Arguments:
+#   1 - Target block device
+get_dev_label() {
+	lsblk -nlo label "${1}"
+}
+
 # Output the filesystem type for the specified block device.
 # Arguments:
 #   1 - Target block device
@@ -159,5 +166,84 @@ regenerate_uuid() {
 
     new_uuid="$(get_dev_uuid "$dev")"
     echo "${new_uuid}"
+    return 0
+}
+
+# Format the specified partition with a new filesystem of the same type,
+# or ext4 if no filesystem is present.
+#
+# Arguments:
+#   1 - Target block device
+#   2 - Filesystem label
+# Returns:
+#   0 - Success
+#   1 - Failure
+reformat() {
+	dev=$1
+	label=$2
+	fstype=$(get_dev_fstype "${dev}")
+	cmd="mkfs.ext4 -E lazy_itable_init=0,lazy_journal_init=0 -O ^64bit,^metadata_csum -i 8192 -F -L ${label}"
+	if [ "$fstype" = "vfat" ]; then
+		cmd="mkfs.vfat -F 32 -n ${label} -S 512"
+	fi
+	if ! eval "${cmd}" "${dev}"; then
+		return 1
+	fi
+	return 0
+}
+
+# Set a Balena filesystem label to the specified device.
+# Arguments:
+#   1 - Target block device
+#   2 - Filesystem label
+# Returns:
+#   0 - Success, new label in stdout
+#   1 - Failure
+relabel() {
+    dev=$1
+    label=$2
+    fstype=$(get_dev_fstype $dev)
+
+    # Filesystem type specific quirks
+    case $fstype in
+        vfat)
+            # mlabel doesn't work on file directly. It needs a drive to file
+            # mapping in its configuration.
+            drive=a:
+	    echo "drive ${drive} file=\"$dev\" exclusive" > /etc/mtools.conf
+            cmd="mlabel -s"
+            if ! eval "${cmd}" "${drive}:${label}"; then
+                return 1
+            fi
+            ;;
+        ext*)
+            # tune2fs refuses to work when the filesystem was not
+            # freshly checked.
+            # Remount to update lastmount time to current time
+            # Otherwise in systems with no RTC lastmount could be in the future
+            # and e2fsck does not update the last filesystem check time
+            if [ -e /etc/e2fsck.conf ] && grep broken_system_clock /etc/e2fsck.conf > /dev/null; then
+                broken_system_clock=$(grep broken_system_clock /etc/e2fsck.conf | cut -d "=" -f2)
+                    if [ "${broken_system_clock}" = "1" ]; then
+                        update_mounttime "$dev"
+                    fi
+            fi
+            if ! e2fsck -fp "$dev"; then
+		return 1
+            fi
+            cmd="echo y | EXT2FS_NO_MTAB_OK=1  tune2fs -O ^64bit,^metadata_csum"
+            if ! eval "${cmd}" "${dev}"; then
+                return 1
+            fi
+            cmd="echo y | EXT2FS_NO_MTAB_OK=1  tune2fs -L ${label}"
+            if ! eval "${cmd}" "${dev}"; then
+                return 1
+            fi
+            ;;
+        *) ;;
+        esac
+
+    new_label="$(get_dev_label "$dev")"
+    echo $new_label
     return 0
 }
