os-helpers-fs: add shared wait4udev function
This allows to share this function between the different device
integration cryptsetup implementations.

Change-type: patch
Signed-off-by: Alex Gonzalez <alexg@balena.io>

diff --git a/meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-fs b/meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-fs
--- a/meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-fs
+++ b/meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-fs
@@ -272,3 +272,35 @@ get_internal_device() {
     done
   done
 }
+
+wait4udev() {
+    # Wait for udev processing of a DM device to finish
+    #
+    # After cryptsetup luksOpen returns to shell, udev events initializing
+    # the DM device are still being generated in the background.
+    # 95-dm-notify.rules will notify dmsetup when udev processing is finished
+    # but we found no way to hook to this from shell.
+    #
+    # This function waits for a particular udev env variable to be defined
+    # on the specified device. This is not the cleanest solution but it works
+    # for this use-case - it indicates the last necessary udev event is being
+    # processed and, if necessary from a shell, a subsequent settle will block
+    # until the processing finishes.
+    #
+    # The function will fail if the variable does not appear in a reasonable amount of time.
+
+    DM_DEVICE="$1"
+
+    I=0
+    # DM_UDEV_RULES_VSN is the last variable that 10-dm.rules defines for an active device
+    while ! udevadm info "${DM_DEVICE}" | grep -q "DM_UDEV_RULES_VSN=2"; do
+        if [ "${I}" -gt 4 ]; then
+            return 1
+        fi
+
+        sleep 1
+        I=$["${I}" + 1]
+    done
+
+    return 0
+}
