Check and get service lockfiles on HUP reboot
This is so that the HUP reboot doesn't interrupt
any user service processes.

Change-type: patch
Signed-off-by: jaomaloy <jao.maloy@balena.io>

diff --git a/meta-balena-common/recipes-containers/hostapp-update/files/hostapp-update b/meta-balena-common/recipes-containers/hostapp-update/files/hostapp-update
--- a/meta-balena-common/recipes-containers/hostapp-update/files/hostapp-update
+++ b/meta-balena-common/recipes-containers/hostapp-update/files/hostapp-update
@@ -16,6 +16,24 @@ run_current_hooks_and_recover () {
 	exit 1
 }
 
+check_locks_and_reboot() {
+  locks=$(find /tmp/balena-supervisor/services -name updates.lock)
+  # Check all user service locks in their directories, if none exists
+  # lock for each service directory.
+  for lock in ${locks}; do
+    exec {FD}<"${lock}"
+    if ! flock -nx $FD; then
+      echo "${lock} exists, cannot proceed with hostOS update."
+      exec {FD}>&-
+      return 1
+    fi
+    exec {FD}>&-
+  done
+
+  echo "No user service lock exists, rebooting now..."
+  reboot
+}
+
 local_image=""
 remote_image=""
 reboot=0
@@ -156,5 +174,9 @@ mv "$SYSROOT/counter.new" "$SYSROOT/counter"
 sync -f "$SYSROOT"
 
 if [ "$reboot" = 1 ]; then
-	reboot
+  # Check all user service locks so that we are not interrupting any
+  # user process. If there are no locks, get the locks and then perform
+  # a reboot.
+  echo "Checking all user services for present locks..."
+  until check_locks_and_reboot; do sleep 1; done
 fi
